databases:
  - name: cargaclick-db
    plan: free
    databaseName: cargaclick_production
    user: cargaclick

services:
  - type: web
    name: cargaclick
    runtime: docker             # usa o Dockerfile da raiz
    plan: starter               # pode trocar pra free ou paid
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /up

    # Executa migrations antes de liberar o deploy
    preDeployCommand: "bundle exec rails db:migrate"

    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_MASTER_KEY
        sync: false   # você cola manualmente no painel da Render
      - key: DATABASE_URL
        fromDatabase:
          name: cargaclick-db
          property: connectionString


