services:
  - type: web
    name: cargaclick
    runtime: docker          # ✅ em vez de "env: docker"
    plan: starter
    dockerfilePath: ./Dockerfile

    # roda as migrações antes do deploy
    preDeployCommand: "bundle exec rails db:migrate"

    # variáveis de ambiente padrão para Rails em produção
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_MASTER_KEY
        sync: false
      # O Render injeta DATABASE_URL automaticamente se você usar o Postgres do Render
      # Caso contrário, defina aqui:
      # - key: DATABASE_URL
      #   value: postgres://usuario:senha@host:5432/cargaclick_production
i
