databases:
  - name: cargaclick-db
    plan: free
    databaseName: cargaclick_production
    user: cargaclick

services:
  - type: web
    name: cargaclick
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_MASTER_KEY
        sync: false         # você cola manualmente no dashboard da Render
      - key: DATABASE_URL
        fromDatabase:
          name: cargaclick-db
          property: connectionString



