services:
  - type: web
    name: cargaclick
    runtime: docker          # usa o Dockerfile da raiz
    plan: starter
    dockerfilePath: ./Dockerfile

    # Roda migrações antes de iniciar
    preDeployCommand: "bundle exec rails db:migrate"

    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_MASTER_KEY
        sync: false
      # Render já injeta DATABASE_URL se você criar Postgres lá.
      # Caso queira usar outro banco, defina manualmente:
      # - key: DATABASE_URL
      #   value: postgres://usuario:senha@host:5432/cargaclick_production



