services:
  - type: web
    name: cargaclick
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile

    # Executa as migrações antes de liberar o deploy
    preDeployCommand: "bundle exec rails db:migrate"

    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_MASTER_KEY
        sync: false   # você adiciona a master key no painel da Render

      # O Render injeta automaticamente DATABASE_URL se você criar um Postgres lá.
      # Caso queira usar seu próprio banco, descomente e configure:
      # - key: DATABASE_URL
      #   value: postgres://usuario:senha@host:5432/cargaclick_production


