default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # A linha abaixo faz o Rails usar a DATABASE_URL se estiver definida.
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: cargaclick_development

test:
  <<: *default
  database: cargaclick_test

production:
  <<: *default
  # Em produção, não precisa mais definir database/username/password manualmente,
  # pois o Rails usará a DATABASE_URL completa definida no Render.
